version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: email_intelligence_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  backend:
    image: 111-backend:latest
    command: bash -c "pip install slowapi websockets && uvicorn main:app --host 0.0.0.0 --port 8000"
    container_name: email_intelligence_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/email_intelligence_db
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - huggingface_cache:/root/.cache/huggingface
    restart: unless-stopped

volumes:
  mongodb_data:
  huggingface_cache:
